### ISSUE TITLE
[SUGGESTION] Add source with already added this menu

### ISSUE THREAD

**Issue by jon4dev** [zxvnme/zgui#13]
As in the title of this topic I have suggestions to add a ready-made source with this menu, because many people can't add it to their cheats and such a ready-made source will help a lot ;)

**Comment by wiotq** [comment]
It's pretty easy to add this menu to your source.
I'll create example but Im not sure which game i should use.

**Comment by zxvnme** [comment]
#2

**Comment by jon4dev** [comment]
Ok, jeżeli nie chcecie zrobić gotowego źródła z tym menu to podajcie mi chociaż najłatwiejsze źródło do dodania tego menu

**Comment by jon4dev** [comment]
Ok, if you don't want to make a ready-made source with this menu, give me at least the easiest source to add this menu.
