### ISSUE TITLE
Jak dodac te menu ?

### ISSUE THREAD

**Issue by lakstick** [zxvnme/zgui#2]
Jak dodac te menu mozesz jakoś bardziej to wytłumaczyc?

Czy byłbyś wstanie dodać takie menu do stickrpghooka? byłbym bardzo wdzięczny

**Comment by wiotq** [comment]
Wszystko znajduje sie w readme
https://github.com/zxvnme/zgui/blob/master/README.md

**Comment by zxvnme** [comment]
@lakstick Please, next time describe your issue using **English** language.
Im closing it for now because as @wiotq already said, detailed tutorial how to add zgui to your project (even with ready code) is in [README](https://github.com/zxvnme/zgui/blob/master/README.md) file.

Best regards.
