### ISSUE TITLE
[REQUEST] window flag nomove

### ISSUE THREAD

**Issue by duxeyo** [zxvnme/zgui#21]
add no move window flag, it can be useful in desktop apps.

**Comment by zxvnme** [comment]
Thanks for requesting a feature.
I will add it ASAP.

But next time make your request more rich in content.

**Comment by zxvnme** [comment]
https://github.com/zxvnme/zgui/commit/798a1d1b1bf0b90c6445818846583b7326f03cad

Best regards.
