### ISSUE TITLE
string_view refusing to work.

### ISSUE THREAD

**Issue by stagfag** [zxvnme/zgui#45]
I know it may have nothing to do with the framework, but std::string_view doesn't work, even when included in the same file. 

["namespace 'std' has no member 'string_view'"](https://i.imgur.com/K9YAdTG.png)

I am using Visual Studio 2019, with 2013 and 2017 redistributables installed.

**Comment by danielkrupinski** [comment]
Make sure C++17 standard is selected in your project settings.

**Comment by zxvnme** [comment]
std::string_view was introduced to STL in C++17. As @danielkrupinski said, make sure your language standard is set properly.
