### ISSUE TITLE
[BUG] Game crashing when injecting?

### ISSUE THREAD

**Issue by joshcancode** [zxvnme/zgui#49]
For some reason, injecting the cheat I'm working on causes my game to immediately crash. Here is my code for the menu.

`Color ToZGUI(zgui::color c) {
	Color col = Color(c.r, c.g, c.b, c.a);
	return col;
}

void line(int x, int y, int x2, int y2, zgui::color c) noexcept {
	g_pSurface->Line(x, y, x2, y2, ToZGUI(c));
}

void rect(int x, int y, int x2, int y2, zgui::color c) noexcept {
	g_pSurface->OutlinedRect(x, y, x2, y2, ToZGUI(c));
}

void filled_rect(int x, int y, int x2, int y2, zgui::color c) noexcept {
	g_pSurface->FilledRect(x, y, x2, y2, ToZGUI(c));
}

void text(int x, int y, zgui::color c, int font, bool center, const char* text) noexcept {
	g_pSurface->DrawSetTextColor(ToZGUI(c));
	g_pSurface->DrawSetTextPos(x, y);
	g_pSurface->DrawSetTextFont(font);
	const char* _input = text;
	size_t length = strlen(_input);
	wchar_t text_wchar[30];
	mbstowcs_s(&length, text_wchar, _input, length);
	g_pSurface->DrawPrintText(text_wchar, strlen(text));
}

void get_text_size(unsigned long font, const char* text, int& wide, int& tall) noexcept {
	g_pSurface->GetTextSize(font, (wchar_t*)text, wide, tall);
}

float get_frametime() noexcept { return g_pGlobalVars->frametime; }

void Menu::Initialize() {
	zgui::functions.draw_line = line;
	zgui::functions.draw_rect = rect;
	zgui::functions.draw_filled_rect = filled_rect;
	zgui::functions.draw_text = text;
	zgui::functions.get_text_size = get_text_size;
}

void Menu::Render()
{
	const unsigned long _font = Globals::CourierNew;

	static bool _pressed = true;

	if (!_pressed && GetAsyncKeyState(VK_INSERT))
		_pressed = true;
	else if (_pressed && !GetAsyncKeyState(VK_INSERT))
	{
		_pressed = false;
		menuOpened = !menuOpened;
	}

	g_InputSystem->EnableInput(!menuOpened);

	if (menuOpened)
	{
		zgui::poll_input("Counter-Strike: Global Offensive");

		if (zgui::begin_window("zgui example window", { 500, 350 }, _font, zgui::zgui_window_flags_none))
		{
			zgui::text("sample checkbox #example");
			zgui::end_window();
		}
	}
}`

Any ideas would be amazing.

**Comment by HighPolyLuna** [comment]
Just realized I forgot to draw them, man I'm tired.

**Comment by HighPolyLuna** [comment]
Still having issues, here's the new code.

`void line(int x, int y, int x2, int y2, zgui::color c) noexcept {
	g_pSurface->DrawSetColor(c.r, c.g, c.b, c.a);
	g_pSurface->DrawLine(x, y, x2, y2);
}

void rect(int x, int y, int x2, int y2, zgui::color c) noexcept {
	g_pSurface->DrawSetColor(c.r, c.g, c.b, c.a);
	g_pSurface->DrawOutlinedRect(x, y, x2, y2);
}

void filled_rect(int x, int y, int x2, int y2, zgui::color c) noexcept {
	g_pSurface->DrawSetColor(c.r, c.g, c.b, c.a);
	g_pSurface->DrawFilledRect(x, y, x2, y2);
}

void text(int x, int y, zgui::color color, int font, bool center, const char* text) noexcept {
	g_pSurface->DrawSetTextColor(color.r, color.g, color.b, color.a);
	g_pSurface->DrawSetTextPos(x, y);
	g_pSurface->DrawSetTextFont(font);
	const char* _input = text;
	size_t length = strlen(_input);
	wchar_t text_wchar[30];
	mbstowcs_s(&length, text_wchar, _input, length);
	g_pSurface->DrawPrintText(text_wchar, strlen(text));
}

void get_text_size(unsigned long font, const char* text, int& wide, int& tall) noexcept {
	g_pSurface->GetTextSize(font, (wchar_t*)text, wide, tall);
}

float get_frametime() noexcept { return g_pGlobalVars->frametime; }

void Menu::Initialize() {
	zgui::functions.draw_line = line;
	zgui::functions.draw_rect = rect;
	zgui::functions.draw_filled_rect = filled_rect;
	zgui::functions.draw_text = text;
	zgui::functions.get_text_size = get_text_size;
}

void Menu::Render()
{
	static bool _pressed = true;

	if (!_pressed && GetAsyncKeyState(VK_INSERT))
		_pressed = true;
	else if (_pressed && !GetAsyncKeyState(VK_INSERT))
	{
		_pressed = false;
		menuOpened = !menuOpened;
	}

	g_InputSystem->EnableInput(!menuOpened);
	if (menuOpened)
	{
		// Start input loop
		zgui::poll_input("Counter-Strike: Global Offensive"); // Improper calling will result in exception.
		// Search in zgui.hh for [input handling] to get more details.

		static bool example = false;
		static int example_int = 10;
		if (zgui::begin_window("zgui example window", { 500, 350 }, Globals::CourierNew, zgui::zgui_window_flags_none))
		{
			zgui::checkbox("sample checkbox #example", example);
			// value before hash is visible ^
			zgui::slider_int("#sample_slider", 0, 40, example_int);
			//                ^ value after hash is hidden"
			//
			// Hashing is demystified in zgui.hh
			// Search for [hashing controls names] to get more details.
			zgui::end_window();
		}
	}
}`

**Comment by zxvnme** [comment]
Dont check if(menuOpened) before drawing. zgui has its own checks in zgui.cpp at the top of the file in global_config struct.

**Comment by cyanidee** [comment]
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug

**Comment by cyanidee** [comment]
Closing the issue as the OP is not providing any helpful information.
