### ISSUE TITLE
[BUG] can not open zgui.cc

### ISSUE THREAD

**Issue by Shemincheat** [zxvnme/zgui#52]
its trying to reference a file thats not used or referenced saying cannot open source file zgui-master\zgui.cc

https://imgur.com/a/1PlpEzh

**Comment by KrekBuk** [comment]
I have the same problem. Please fix.

**Comment by zxvnme** [comment]
https://stackoverflow.com/a/9754017

**Comment by Shemincheat** [comment]
SOo that doesnt help me.....
