### ISSUE TITLE
[BUG] Elements don't get triggered.

### ISSUE THREAD

**Issue by NaiJii** [zxvnme/zgui#60]
**Describe the bug**
Sliders, Comboboxes, Keybind, every zgui's elements (except the checkbox) don't get triggered if you didn't trigger a tab or checkbox before. GIF : https://i.imgur.com/CqSEziy.gifv
Also bug when you first open the menu.

**To Reproduce**
1. Change tab
2. Try to change sliders' values or whatever

**Expected behavior**
The selected element should get triggered.

**Comment by cyanidee** [comment]
but there are no tabs in zgui LULW

**Comment by NaiJii** [comment]
> but there are no tabs in zgui LULW

Oops, thought it'll also happen when the menu gets injected, my bad. 
Closed

**Comment by zxvnme** [comment]
As said above, there are no official support for creating tabs in zgui.
