### ISSUE TITLE
[BUG] Game interference.

### ISSUE THREAD

**Issue by xorBling** [zxvnme/zgui#62]
When my menu is open I can still shoot my weapon

Gif: https://gyazo.com/6a641474a6578ff4d3e6c9209af4677c

I have LockCursor hooked

**Comment by NaiJii** [comment]
You have to disable input (from inputsystem) as well.

**Comment by NekoRem** [comment]
if you don't know how to do this... i disabled input (from input system) in this source
https://github.com/NekoRem/alphauc-sdk-zgui

**Comment by zxvnme** [comment]
@NekoRem Why did u do separated repository with alpha's source and your modifications?
There's zgui embedded in original repository and you could contribute to it.

**Comment by xorBling** [comment]
fixed thanks y'all
