### ISSUE TITLE
Menu only works when I turn on the consoles in CS:Go

### ISSUE THREAD

**Issue by lakstick** [zxvnme/zgui#64]
I have a mistake in the csgo game in the title.
when I don't have the console turned on, I can't choose anything from the menu and if I have it turned on, yes.

**Comment by Chrisdies** [comment]
We don't speak monkey please translate to english

**Comment by zxvnme** [comment]
We are not fairies, please provide more information about the problem and use a debugger.
Your issue is related to game hacking and the only support that you will get is support with zgui itself.

**Comment by smefpw** [comment]
I'm guessing you mean, that when the console is open you can then select elements on the menu.
You need to hook LockCursor...

**Comment by lakstick** [comment]
> I'm guessing you mean, that when the console is open you can then select elements on the menu.
> You need to hook LockCursor...

Yeah, that is it ;) thank you so much
